#ifndef     EXT_INT_CFG_H_
#define     EXT_INT_CFG_H_

#define     EXT_INT0_INIT_STATE		EXT_INT0_ENABLE
#define     EXT_INT1_INIT_STATE		EXT_INT1_DISABLE
#define     EXT_INT2_INIT_STATE		EXT_INT2_DISABLE

#define     EXT_INT0_INIT_MODE		EXT_INT0_LOWLEV
#define     EXT_INT1_INIT_MODE		EXT_INT1_RISE
#define     EXT_INT2_INIT_MODE		EXT_INT2_FALL

#endif
